# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='e_mail',
            field=models.EmailField(max_length=50),
        ),
    ]
