# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addr', '0002_auto_20180620_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='memo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
